[package]
name = "rust-shaku-practice4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.13.1"
shaku = "0.6.2"
