[package]
name = "rust-shaku-practice6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shaku = { version = "0.6.2", features = ["derive"] }
chrono = "0.4"